exp_name: augmented
proj_dir: ./

datasets:
  dataset_name: retro
  debugging: 
    overfit: False
    subset: ~
  train:
    data_root: data/uspto-50k/patents40k_x5MSShuf.csv
    batch_size: 32
    num_workers: 4
  val:
    data_root: data/uspto-50k/patents40k_x5MSShuf.csv
    batch_size: 32
    num_workers: 1

train:
  total_iters: 600
  load_iter: auto
  checkpoint_interval: 1
  print_interval: 100  # by steps
  val_interval: 1

  pretrained_paths:
    net: ~

  optimizer: 
    type: adam
    cycle_every: 100
    l_factor: !!float 20.0
    warmup: !!float 16000.0
    opt_params:
      lr: !!float 1e-4
  
  # scheduler:
  #   type: cyclic
  #   factor: 20
  #   sched_params:

model:
  name: retro_seq2seq
  net:
    type: AugmentedTransformer
    opt:
      n_block: 3
      n_head: 2
      embed_dim: 64
      hidden_dim: 512
      key_dim: 64
      maxlen: 1000

  weights_to_average: [600, 700, 800, 900, 999]
  temperature: 1.2
  beam_size: 5
  max_decoding_len: 160

  use_torch_compile: False
  
  tokenizer:
    src_vocab: vocab/src.vocab
    tgt_vocab: vocab/tgt.vocab