exp_name: augmented

datasets:
  dataset_name: retro
  data_path: uspto-50k/patents40k_x5MSShuf.csv
  debugging: 
    overfit: False
    subset: ~
  train:
    batch_size: 2
    num_workers: 4
  val:
    batch_size: 2
    num_workers: 1

train:
  total_iters: 600000
  load_iter: auto
  checkpoint_interval: 5000
  print_interval: 100
  val_interval: 10000

  pretrained_paths:
    net: ~

  optimizer: 
    type: adam
    cycle_every: 100
    l_factor: !!float 20.0
    warmup: !!float 16000.0
    opt_params:
      lr: !!float 1e-4
  
  # scheduler:
  #   type: cyclic
  #   factor: 20
  #   sched_params:

model:
  name: RetroSeq2SeqModel
  net:
    type: AugmentedTransformer
    opt:
      n_block: 3
      n_head: 2
      embed_dim: 64
      hidden_dim: 32
      key_dim: 20
      maxlen: 160

  temperature: 1.2
  topks: [1, 3]
  beam_size: 5

  use_torch_compile: False
  
  tokenizer:
    src_vocab: vocab/src.vocab
    tgt_vocab: vocab/tgt.vocab